apiVersion: apps/v1
kind: Deployment
metdata:
  name: cart
  labels:
    service: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      service: cart
  template:
    metadata:
      name: cart
      labels:
        service: cart
    spec:
      imagePullSecrets:
      - name: dock
      containers:
      - name: cart
        image: sphari/cart:23
        env:
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 8080
