apiVersion: apps/v1
kind: Deployment
metdata:
  name: catalogue
  labels:
    service: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      service: catalogue
  template:
    metadata:
      name: catalogue
      labels:
        service: catalogue
    spec:
      imagePullSecrets:
      - name: dock
      containers:
      - name: catalogue
        image: sphari/catalogue:2
        env:
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 8080
