apiVersion: apps/v1
kind: Deployment
metdata:
  name: dispatch
  labels:
    service: dispatch
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dispatch
  template:
    metadata:
      name: dispatch
      labels:
        service: dispatch
    spec:
      imagePullSecrets:
      - name: dock
      containers:
      - name: dispatch
        image: sphari/dispatch:2
        env:
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi

