apiVersion: apps/v1
kind: Deployment
metdata:
  name: ratings
  labels:
    service: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ratings
  template:
    metadata:
      name: ratings
      labels:
        service: ratings
    spec:
      imagePullSecrets:
      - name: dock
      containers:
      - name: ratings
        image: sphari/ratings:3
        env:
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 80
        redinessProbe:
          httpGet:
            path: /_health
            port: 80
          initialDeplaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30
          successThreshold: 1
      restartPolicy: Always
