apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  serviceName: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      imagePullSecrets:
      - name: dock
      containers:
      - name: redis
        image: redis:4.0.6
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /mnt/redis
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolume
metadata:
- name: data
spec:
  accessModes: ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
