apiVersion: apps/v1
kind: Deployment
metdata:
  name: user
  labels:
    service: user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user
  template:
    metadata:
      name: user
      labels:
        service: user
    spec:
      imagePullSecrets:
      - name: dock
      containers:
      - name: user
        image: sphari/user:3
        env:
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 8080
      restartPolicy: Always
