apiVersion: apps/v1
kind: Deployment
metdata:
  name: web
  labels:
    service: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      name: web
      labels:
        service: web
    spec:
      imagePullSecrets:
      - name: dock
      containers:
      - name: web
        image: sphari/web:3
        env:
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 8080
      restartPolicy: Always
